project_id = "uhktrhswjsjflwcudway"

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]  
verify_jwt = false

[functions.verify-pending-payments]
verify_jwt = false