// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhktrhswjsjflwcudway.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoa3RyaHN3anNqZmx3Y3Vkd2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjQyNTYsImV4cCI6MjA2Njk0MDI1Nn0.LXNpLw_SwqlHe4ThFoXPWOGsSl15wiX5rgFfgmySd_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});